version: '3'
services:
 db:
  image: postgres
  volumes:
    - ./tmp/db:/var/lib/postgresql/data
  environment:
    POSTGRES_DB: "Alien_Apocalypse"
    POSTGRES_USER: "yasmin"
 web:
  build: .
  entrypoint: /app/docker-entrypoint.sh
  command: ["rails", "server", "-b", "0.0.0.0"]
  environment: 
    RAILS_ENV: development
  volumes:
   - .:/app
  ports:
   - "3000:3000"
  links:
   - db
  depends_on:
   - db
